MD ALUNOS
CD ALUNOS
MD Estagio
CD Estagio
MD Apresentacao-CRPE
MD Cartilhascomorientacoes
MD ConhecaaLeidoEstagio
CD ConhecaaLeidoEstagio
MD ApresentacaoComposicaoeNormas
CD ..
MD DicasUteis
MD EstagienoCefet-MG
MD Legislacao
MD Maisinformacoes
MD OrganogramaEstagio
MD Quemequem
MD Superior
MD Tecnico
CD ..
MD Horarios
CD Horarios
MD -Cursostecnicos
MD -Graduacao
MD -Laboratorios
CD ..
MD Monitoria
MD NormasAcademicas-Aluno
MD RedeWi-Fi-Aluno
MD Requerimentoseformularios
CD Requerimentoseformularios
MD FormulariosCRCADV
CD ..
MD RestauranteEstudantil
MD Calendario
CD ..
MD CestaCultural
MD COMUNICACAO
CD COMUNICACAO
MD AComissaodeComunicacao
MD Enviodemensagensvialistasdeemail.
MD Membros
MD PublicacoesnositedoCampusDivinopolis
CD ..
MD CoordenacaodeAssuntosAcademicos
MD CoordenacaodeGestaodeLaboratorios
MD CURSOS
CD CURSOS
MD CursosdeGraduacao.
MD CursosdePos-graduacao
CD CursosdePos-graduacao
MD LatoSensu
MD StrictoSensu-MestradoPROFEPT
CD ..
MD CursosTecnicos.
CD ..
MD Eletrica
MD ERE-InformacoesLocais
MD ERE-QuadrodeContatos
MD ESTUDENOCEFET-MG
CD ESTUDENOCEFET-MG
MD Cursostecnicos
MD Graduacao
MD Pos-Graduacao
CD ..
MD FormacaoGeral
MD HorariodosPlantoesdeRecuperacao2019
MD Informatica
MD INSTITUCIONAL
CD INSTITUCIONAL
MD AcessoRestrito
MD Apresentacao
MD Comissoes
CD Comissoes
MD BrigadadeEmergencia
CD BrigadadeEmergencia
MD Apresentacao
MD Brigadistas
MD Eventos(cursos,treinamentos,etc.)
CD ..
MD ComissaoEleitoralLocal
CD ..
MD ContatosdosServidores
MD FuncoesSetores
MD Gestao
MD Localizacao
MD Memorial
MD Organograma
MD Ouvidoria
MD Professores
MD TecnicosAdministrativos
MD Trabalheconosco
CD ..
MD InstrucoesNormativas
MD JornalNos
MD MapadoSite
MD Mecanica
MD OCAMPUSDIVINOPOLIS
CD OCAMPUSDIVINOPOLIS
MD Congregacao
CD Congregacao
MD Apresentacaocomposicaoenormas
MD Atas
MD Calendariodasreunioes
MD Resolucoes
CD ..
MD DepartamentodeEngenhariaMecatronica-DEM-DV
MD DepartamentodeFormacaoGeral-DFG-DV
MD DepartamentodeInformatica,GestaoeDesign-DIGD-DV
MD DiretoriadoCampus
CD DiretoriadoCampus
MD ADiretoria
MD PortariasdaDiretoria
MD SecretariadaDiretoria
CD ..
MD Setores
CD Setores
MD Biblioteca-ProfessorAntonioJoseNogueiraGontijo-
MD CoordenacaodeAdministracao
MD CoordenacaodeExtensaoeDesenvolvimentoComunitario
MD CoordenacaodeGestaodePessoas
MD CoordenacaodePoliticaEstudantil
CD CoordenacaodePoliticaEstudantil
MD ACDEDV
MD Equipe
MD ProgramaseAcoesDesenvolvidas
CD ..
MD CoordenacaodeRegistroAcademico
MD CoordenacaodeServicosGerais
MD CoordenacaoPedagogica
MD NucleodeTecnologiadaInformacaoeComunicacao
CD ..
CD ..
MD OrganogramaInstitucional
MD PAIS
MD PESQUISAEEXTENSAO
CD PESQUISAEEXTENSAO
MD Extensao
CD Extensao
MD Apresentacao.
MD CIT-Coord.deInovacaoTecnologica
MD Contato.
MD GuiaseFormularios
CD GuiaseFormularios
MD ManualdeExtensao
MD Normas
CD ..
MD ProgramaseProjetos
CD ProgramaseProjetos
MD AEscritadeSiComoInstrumentodeVisibilidadeparaosTerceirizadosdoCEFET-MG
MD FormacaodeProfessores
MD IniciacaoemProgramacaoeRoboticaparaEscolasdoEnsinoFundamentaldeDivinopolis/MG
MD MOVAP-MovimentoempreendedordovaledorioPara/MG
MD NascenteIncubadoradeEmpresasdoCEFET-MG
CD NascenteIncubadoradeEmpresasdoCEFET-MG
MD Contato-Incubadora
CD ..
MD Pre-CEFETDivinopolis
MD ProgramaAzimuteNorte
CD ProgramaAzimuteNorte
MD Apresentacao-AzimuteNorte
CD ..
MD ProjetosdeExtensaoVoltadosparaoenfrentamentodaCOVID-19
MD Sementes
CD ..
CD ..
MD Pesquisa
CD Pesquisa
MD BIC-JR-PIBIT-PIBIC
MD META
CD META
MD 2014.
MD 2015.
CD ..   '
MD MonitoramentoSocioeconomicodoSetordoVestuario
MD NUPEV
MD SemanaC&T
CD SemanaC&T
MD 2013
MD 2014
MD 2015
CD ..
CD ..
CD ..
MD Portarias
MD ProcessoSeletivodoCursodeMestradoProfissionalemEducacaoProfissionaleTecnologicaemredenacional-Turma2020
MD ProducaodeModa
MD Resolucoes
MD SERVIDOR
CD SERVIDOR
MD CentraldeServicosdeTI
MD FormularioseRequerimentos
MD Manuais
CD Manuais
MD LicencasMedicas-Orientacoes
CD ..
MD NormasAcademicas-Servidor
MD RedeWi-Fi-Servidor
MD SistemasInstitucionais
MD Solicitacaodeveiculos.
CD ..
CD ..
MD SobreaExtensao
MD Tutoriais